### ISSUE TITLE
CMD Tool 

### ISSUE THREAD

**Issue by sqlpha** [janmotl/linkifier#8]
Hi janmotl,

This is an absolute good tool! 
I'd appreciate if there is some support of command line mode.
Because I don't know too much about java, I try to use Python to call some class of this module, but it failed.
Do you any plan about that?

Best regards,
Ziyang

**Comment by janmotl** [comment]
Hi Ziyang,

thank you for your kind words. 

1. Download a development build [linkifier_3.2.9.zip](https://github.com/janmotl/linkifier/files/8103473/linkifier.zip)
2. Try something like: `java -cp ./linkifier-3.2.9.jar main.CLI` in Linkifier directory.

All that it does is that it reads `connection.properties`, executes Linkifier and returns all possible outputs that it can. If you want something more, propose the API.

**Comment by sqlpha** [comment]
> Hi Ziyang,
> 
> thank you for your kind words.
> 
> 1. Download a development build [linkifier_3.2.9.zip](https://github.com/janmotl/linkifier/files/8103473/linkifier.zip)
> 2. Try something like: `java -cp ./linkifier-3.2.9.jar main.CLI` in Linkifier directory.
> 
> All that it does is that it reads `connection.properties`, executes Linkifier and returns all possible outputs that it can. If you want something more, propose the API.

Thank you for your quick reply!

I managed to run it and get results.

Really appreciate the work you did.

Best regards,
Ziyang
